### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by alanmilinovic** [JJFourie/HomeAssistant-PulseAudio-Disable#7]
This solution is not working in my case. I followed all the stps but no luck. There isn't any audio. Tried to run command manually and as a service.

**Comment by JJFourie** [comment]
I created the script to address two issues I experienced with the "hassio_audio" container, namely (1) high CPU consumption and (2) verbose logging that just wastes system resources and wear out your storage.   
    
Problem is that I'm not a PulseAudio expert, so if suspending PulseAudio does not fix your audio problem I unfortunately can't help much. Maybe you can have a look on the [Home Assistant](https://community.home-assistant.io/) or [PulseAudio](https://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/User/Community/) community websites?

**Comment by EDIflyer** [comment]
So I've found that manually running the command `docker exec -it hassio_audio pactl load-module module-suspend-on-idle` mentioned in [README.md](https://github.com/JJFourie/HomeAssistant-PulseAudio-Disable#readme) does the trick (drops pulseaudio CPU from continuously using 2.8% of CPU to basically 0% on my Pi 4 8GB, dropping overall idle CPU usage from 4% to 2% and mean temp from 40C to 38C - the CPU frequency (ondemand governor) seemed to be stuck at 1Ghz rather than 600Mhz with pulseaudio continually running).  However when I tried running the service/script setup on the main page of this repo it didn't seem to stop it - I'm not sure if related to PR #8?

However given this Docker command works so well for me I therefore instead have set it to run automatically after reboot via crontab instead. I wrapped it in a wee script complete with logging and just added the following via `crontab` for it to run 5 min after reboot and hourly thereafter.  I wasn't sure if only needed at reboot or if the service re-enabled itself hence why I've got it logging for now and can always change to only on reboot if it turns out it's not required:

I created a new file `pa-dockersuspend.sh` in `/home/pi/Scripts` and made it executable:
``` bash
#!/bin/bash
#
# Suspend Pulse Audio via Docker for HASSIO issue
# Alan Robertson (December 2022) based on command from https://github.com/JJFourie/HomeAssistant-PulseAudio-Disable
#
# Remember to run the docker exec command with as -t not -it as -i implies an interactive terminal
# which won't be available via crontab (see https://stackoverflow.com/a/37410430/8179476)
#
echo $(date) >> /home/pi/Scripts/pa-suspend.log
docker exec -t hassio_audio pactl load-module module-suspend-on-idle >> /home/pi/Scripts/pa-suspend.log
echo "----------------------------" >> /home/pi/Scripts/pa-suspend.log
```

I then ran `crontab -e` and added the following to run both at reboot and hourly - as I say I'll keep an eye on things for a few days and if not required as frequently will adjust/remove the 2nd line:
``` bash
@reboot sleep 300 && /home/pi/Scripts/pa-dockersuspend.sh
0 * * * * /home/pi/Scripts/pa-dockersuspend.sh
```

**Comment by alanmilinovic** [comment]
Why not making a service like I did. That will run on boot.

https://github.com/alanmilinovic/HomeAssistant-PulseAudio-Disable

For my this solution is working. Will close the case.

**Comment by EDIflyer** [comment]
@alanmilinovic I didn't realise you'd found a fix as your previous comment didn't mention it. Personally I've just gone for a very simple approach, will be interested to see if it needs to run again or not, if not I'll make it run that one command only at reboot. Main thing is we're getting sorted with a workaround for this annoying bug, whatever the route! 👍

**Comment by JJFourie** [comment]
@alanmilinovic , @EDIflyer 
End of November already I created a new version ("**_v2**") of the shell script that first checks if the ```"run"``` config file is still at its original location before updating it. If not found, it means that the new version "2022.04.1" of the ```hassio_audio``` container is already implemented. In this new version of the container PulseAudio is _not_ running with verbose logging anymore, so there is no need to update the config file. 
To prevent confusion I will make a more prominent comment in the ReadMe that there is a new version of the script and that it should be used.

By the way, you can **disable bluetooth** (on the RPi) by default by adding a line to the related ```config.txt``` as follows:
```echo "dtoverlay=disable-bt" | sudo tee -a /boot/config.txt```
And to disable the (systemd) service that initializes the bluetooth modem:
```sudo systemctl disable hciuart```

To disable audio should you want that, in ```/boot/config.txt``` change ```dtparam=audio=on``` to ```dtparam=audio=off```

**Comment by alanmilinovic** [comment]
Tnx for the comment. I already realized that you created a new version and merged your changes with my version on github.

In the meantime, I migrated everything from rpi to nuc, as rpi is very slow and I lost my patience. :)

Regarding bluetooth, I am talking about module inside container, not on host machine:
`docker exec -i hassio_audio pactl unload-module module-bluetooth-discover`
